# -*- coding: utf-8 -*-
"""Titanic_Survival_Priction using Machine Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKnxrVvFnQHc79Qf06BxgRyFMWOW8jnE
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, mean_squared_error, r2_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report

import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv("/content/Titanic-Dataset.csv")

print("First 5 rows of dataset")
print(data.head())

print("\nDataset Info")
print(data.info())

print("\nMissing Values")
print(data.isnull().sum())

# Fill missing Age with mean
data['Age'].fillna(data['Age'].mean(), inplace=True)

# Fill missing Embarked with most frequent value
data['Embarked'].fillna(data['Embarked'].mode()[0], inplace=True)

# Drop Cabin column (too many missing values)
data.drop(columns=['Cabin'], inplace=True)

# Drop unnecessary columns
data.drop(columns=['Name','Ticket','PassengerId'], inplace=True)

le = LabelEncoder()

data['Sex'] = le.fit_transform(data['Sex'])
data['Embarked'] = le.fit_transform(data['Embarked'])

print("\nProcessed Dataset")
print(data.head())

X = data.drop('Survived', axis=1)
y = data['Survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("\nTraining data size:", X_train.shape)
print("Testing data size:", X_test.shape)

# Logistic Regression Model
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

print("\nModel Training Completed")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\nModel Evaluation Results")
print("Accuracy :", accuracy)
print("Mean Squared Error :", mse)
print("R2 Score :", r2)

tree_model = DecisionTreeClassifier()

tree_model.fit(X_train, y_train)

y_pred_tree = tree_model.predict(X_test)

print("\nDecision Tree Accuracy :", accuracy_score(y_test, y_pred_tree))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix")
print(cm)

from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test, y_pred))

plt.figure()
sns.countplot(x='Survived', data=data)
plt.title("Survival Count")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.ylabel("Number of Passengers")
plt.show()

plt.figure()
sns.countplot(x='Sex', hue='Survived', data=data)
plt.title("Survival by Gender")
plt.xlabel("Gender")
plt.ylabel("Passenger Count")
plt.show()

plt.figure()
sns.histplot(data['Age'], bins=30, kde=True)
plt.title("Age Distribution of Passengers")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

plt.figure()
sns.countplot(x='Pclass', hue='Survived', data=data)
plt.title("Passenger Class vs Survival")
plt.xlabel("Passenger Class")
plt.ylabel("Passenger Count")
plt.show()

plt.figure()
sns.heatmap(data.corr(), annot=True)
plt.title("Feature Correlation Heatmap")
plt.show()

plt.figure()
sns.boxplot(x='Survived', y='Fare', data=data)
plt.title("Fare vs Survival")
plt.xlabel("Survived")
plt.ylabel("Fare")
plt.show()

